export const LOAD_COLORSET = 'LOAD_COLORSET'
export const SAVE_COLORSET = 'SAVE_COLORSET'

export const ADD_COLORSET = 'ADD_COLORSET'
export const REMOVE_COLORSET = 'REMOVE_COLORSET'
export const SELECT_COLORSET = 'SELECT_COLORSET'

export const ADD_CATEGORICAL_PALETTE = 'ADD_CATEGORICAL_PALETTE'
export const REMOVE_CATEGORICAL_PALETTE = 'REMOVE_CATEGORICAL_PALETTE'

export const ADD_SEQUENTRIAL_PALETTE = 'ADD_SEQUENTIAL_PALETTE'
export const REMOVE_SEQUENTRIAL_PALETTE = 'REMOVE_SEQUENTIAL_PALETTE'
export const UPDATE_SEQUENTRIAL_PALETTE = 'UPDATE_SEQUENTIAL_PALETTE'

export const ADD_DIVERGING_PALETTE = 'ADD_DIVERGING_PALETTE'
export const REMOVE_DIVERGING_PALETTE = 'REMOVE_DIVERGING_PALETTE'
export const UPDATE_DIVERGING_PALETTE = 'UPDATE_DIVERGING_PALETTE'

export const SHOW_DASHBOARD = 'SHOW_DASHBOARD'

export const loadJSON = (json: string) => ({
  json,
  type: LOAD_COLORSET
})

export const saveJSON = () => ({
  type: SAVE_COLORSET
})

export const selectColorSet = (id: string) => ({
  id,
  type: SELECT_COLORSET
})

export const showDashboard = (show: boolean) => ({
  show,
  type: SHOW_DASHBOARD
})
